### ISSUE TITLE
Finalize GREP 10: Templates

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/greps#11]
We merged it as Draft, and there's also https://github.com/gnuradio/gnuradio/pull/1633, but do we need anything else to make it `Active`? I'm pretty happy with @noc0lour 's work on this.

**Comment by noc0lour** [comment]
I'd like to convert most of the templates automatically with a Python script. Converting every templated block manually will be pretty cumbersome and error-prone. I outlined steps to take to convert templates already in the GREP PR. I already have the code scanning CMakeLists.txt for our custom templates. Now I need to write the replacement part. 

Is it of use to have this GREP `active` without having everything converted?

**Comment by mbr0wn** [comment]
Good question. I consider a GREP to be active when the details are all decided, but before the action happens. This one in particular is going to be work once, and then we keep the GREP as advisory.

**Comment by marcusmueller** [comment]
@noc0lour re automation: as of now, there's 51× .cc.t on next. Many of those do funky special-casing... This will be mind-numbing, tedious, manual work, nevertheless, so I'd really not try to be too smart in your templateriz0r2000+. But I'd really love to have a tool that at least extracts the templated C'tor!

What I'm trying to say: Pareto. Write something that takes what is numbing to do manually, but easy to do automatedly; don't invest too much time into making the automation capable of actually parsing gengen'ed C++. Neither C++ nor gengen is something you actually want to parse.

**Comment by mbr0wn** [comment]
Yeah don't overthink this. We'll only need the automation script once, after all. If there's a script that does a partial conversion, and then the rest needs to be done by hand, we might be able to split the load, too.

**Comment by noc0lour** [comment]
@marcusmueller 51x is quite some,stuff, also we already have a python script generating the templated stuff. Last time I looked at the current template code I just did not have the time to parse it and extract the good part for the conversion.
